# Generated by Django 5.1.7 on 2026-05-20 21:40

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ивента')),
                ('short_description', models.CharField(max_length=120, verbose_name='Краткое описание')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('event_date', models.DateTimeField(verbose_name='Дата проведения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=120, verbose_name='Краткое описание (до 120 символов)')),
                ('full_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Полный текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст')),
                ('gender', models.CharField(max_length=30, verbose_name='Пол')),
                ('race', models.CharField(max_length=100, verbose_name='Раса')),
                ('faction', models.CharField(blank=True, max_length=100, verbose_name='Фракция')),
                ('appearance', models.TextField(verbose_name='Внешность')),
                ('abilities', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Способности')),
                ('magic', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Магия')),
                ('inventory', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Инвентарь')),
                ('biography', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Биография')),
                ('status', models.CharField(choices=[('pending', '⛧ Не проверено'), ('approved', '⚜ Одобрено'), ('declined', '☠ Не одобрено')], default='pending', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администрации')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='characters/main/', verbose_name='Главное изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Анкету',
                'verbose_name_plural': 'Анкеты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='characters/gallery/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_images', to='app0.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='character_gallery', to='app0.characterimage', verbose_name='Галерея'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('discord', models.CharField(blank=True, max_length=100, verbose_name='Discord')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
