# Generated by Django 5.1.7 on 2026-05-24 14:47

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='abilities',
        ),
        migrations.AddField(
            model_name='character',
            name='art_link',
            field=models.URLField(blank=True, verbose_name='Референсы/Арты'),
        ),
        migrations.AddField(
            model_name='character',
            name='combat_skills',
            field=models.TextField(blank=True, verbose_name='Боевые навыки'),
        ),
        migrations.AddField(
            model_name='character',
            name='documents',
            field=models.TextField(blank=True, verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='character',
            name='height_weight',
            field=models.CharField(blank=True, max_length=100, verbose_name='Рост и вес'),
        ),
        migrations.AddField(
            model_name='character',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='characters/music/', verbose_name='Музыка (MP3)'),
        ),
        migrations.AddField(
            model_name='character',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Профессия/Роль'),
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True, verbose_name='Характер'),
        ),
        migrations.AddField(
            model_name='character',
            name='pony_town_skin',
            field=models.URLField(blank=True, verbose_name='Скин в Pony Town'),
        ),
        migrations.AddField(
            model_name='character',
            name='racial_abilities',
            field=models.TextField(blank=True, verbose_name='Расовые способности'),
        ),
        migrations.AddField(
            model_name='character',
            name='voice_link',
            field=models.URLField(blank=True, verbose_name='Голос персонажа'),
        ),
        migrations.AddField(
            model_name='character',
            name='weaknesses',
            field=models.TextField(blank=True, verbose_name='Слабости'),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.CharField(max_length=100, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=models.TextField(verbose_name='Особенности внешности'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='character',
            name='magic',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Магические способности'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя и фамилия, псевдоним'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.CharField(choices=[('pending', '⛧ Не проверено'), ('approved', '⚜ Одобрено'), ('declined', '☠ Не одобрено'), ('edited', '📝 Требует изменений')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='О себе'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app0.character')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
    ]
