# Generated by Django 5.1.7 on 2026-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0002_remove_character_abilities_character_art_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='voice_link',
        ),
        migrations.AddField(
            model_name='character',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='characters/voice/', verbose_name='Голос (аудио)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='art_link',
            field=models.FileField(blank=True, null=True, upload_to='characters/art/', verbose_name='Референсы/Арты (изображение)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='pony_town_skin',
            field=models.ImageField(blank=True, null=True, upload_to='characters/skins/', verbose_name='Скин в Pony Town'),
        ),
    ]
