# Generated by Django 5.1.7 on 2026-05-24 15:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0003_remove_character_voice_link_character_voice_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='art_link',
        ),
        migrations.AddField(
            model_name='character',
            name='art_file',
            field=models.ImageField(blank=True, null=True, upload_to='characters/art/', verbose_name='Референсы/Арты'),
        ),
        migrations.AlterField(
            model_name='character',
            name='biography',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='character',
            name='combat_skills',
            field=models.TextField(blank=True, null=True, verbose_name='Боевые навыки'),
        ),
        migrations.AlterField(
            model_name='character',
            name='documents',
            field=models.TextField(blank=True, null=True, verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фракция'),
        ),
        migrations.AlterField(
            model_name='character',
            name='height_weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Рост и вес'),
        ),
        migrations.AlterField(
            model_name='character',
            name='inventory',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Инвентарь'),
        ),
        migrations.AlterField(
            model_name='character',
            name='magic',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Магические способности'),
        ),
        migrations.AlterField(
            model_name='character',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Профессия/Роль'),
        ),
        migrations.AlterField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True, null=True, verbose_name='Характер'),
        ),
        migrations.AlterField(
            model_name='character',
            name='racial_abilities',
            field=models.TextField(blank=True, null=True, verbose_name='Расовые способности'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weaknesses',
            field=models.TextField(blank=True, null=True, verbose_name='Слабости'),
        ),
    ]
