# Generated by Django 5.1.7 on 2026-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0004_remove_character_art_link_character_art_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='Заметка администратора (только для админов)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reputation',
            field=models.CharField(choices=[('good', '⚜ Хороший постоялец'), ('warning', '⚠️ Оставляет желать лучшего'), ('aggressive', '💀 Агрессивный постоялец'), ('new', '✨ Новый постоялец')], default='new', max_length=20, verbose_name='Репутация'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт/Портфолио'),
        ),
    ]
